### ISSUE TITLE
Add NOUPDATE option to prevent upload if filename exists already

### ISSUE THREAD

**Issue by mishatx** [StEdwardsTeam/PrintToBox#2]
Is there any possibility of a flag to not allow sending of a file if a file with that name already exists?

We have a cron job that sweeps a directory every five minutes to send those files to a shared drive.  The directory is emptied once a day.  I'd like to avoid having 144 versions of files out there.

**Comment by mishatx** [comment]
ideally of course, if a file of that name with the same checksum already exists, assume it is the same and don't send a new file.

**Comment by mishatx** [comment]
Other posibility - force overwrite, so that instead of a new version the file is replaced (ie, deleted and re-uploaded).

**Comment by luyseyal** [comment]
Recapping our offline discussion today:

1. There doesn't seem to be an atomic way of replacing a file entirely
2. You can either:
   * Delete the existing file and upload the new one (two operations)
   * Rename the existing file, upload the new one, and delete the old one (three operations)
3. Given the frequency of updates you are talking about (once every 5 minutes), the chance of a simultaneous upload increases quite a bit which could result in a race condition and the wrong file being uploaded.
4. PrintToBox does not enforce execution/upload order. In addition, in order to prevent file lock contention on the tokens file, it sleeps a random value. This does mean that, under contention, the wrong file version could be the most recent version. With the proposed feature, that would be worse because the most recent version would not exist in Box.com.

I'm going to re-read the operations APIs. Another possibility could be a soft file lock in Box.

**Comment by luyseyal** [comment]
It's time for one of those lock blocking feats 
https://github.com/box/box-java-sdk/issues/16

**Comment by luyseyal** [comment]
This will become a "no update if exists" feature. I have added our other ideas to separate issues.
